name: CI

on:
  push:
    branches: [master]
    paths-ignore: ['**.md']
  pull_request:
    types: [opened, synchronize]
    paths-ignore: ['**.md']

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Ensure go.mod is already tidied
      run: |
        go mod tidy
        (cd hack/tools && go mod tidy)
        git diff -s --exit-code go.sum hack/tools/go.sum
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - run: make vet fmt lint
    - run: make dist
    - uses: superbrothers/actions/krew-plugin-test@master
      with:
        archive: dist/kubectl-view_serviceaccount_kubeconfig-linux-amd64.zip
        manifest: dist/view-serviceaccount-kubeconfig.yaml
        command: kubectl view-serviceaccount-kubeconfig --help
